name: Formatter_app

on:
  push:
    branches: 
    - main

jobs:
  Build_check:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build all
      shell: bash
      run: |
        cmake -H. -B_build
        cmake --build _build
        
  Examples:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build all
      shell: bash
      run: |
        cmake -H. -B_build
        cmake --build _build

    - name: HelloWorldApplication CMake
      shell: bash
      run: |
        ./hello_world_application/hello_world

    - name: SolverApplication CMake
      shell: bash
      run: |
        ./solver_application/solve 1 -5 6